[versions]
kotlin = "1.8.20"
gradle = "8.0.2"
ktLint = "10.3.0"
detekt = "1.19.0"
gradleVersionUpdate = "0.42.0"
googleServices = "4.3.14"
firebaseAppDistribution = "3.0.3"
firebaseCrashlytics = "2.9.2"
firebasePerformance = "1.4.2"
nativeCocoapod = "1.9.0"

# Kotlin Multiplatform Version
kotlinxCoroutines = "1.6.4"
koinCore = "3.4.2"
koinCompose = "1.0.3"
koinAndroid = "3.3.3"
koinAndroidxCompose = "3.4.5"
kotlinxSerializationJson = "1.5.0"
kotlinxDateTime = "0.4.0"
napier = "2.4.0"
ktor = "2.2.3"
sqlDelight = "1.5.5"
multiplatformSettings = "0.8.1"
kmpNativeCoroutines = "0.12.1-new-mm"
buildKonfig = "0.13.3"
kover = "0.6.1"
mockk = "1.12.3"
kotlinxTestResources = "0.2.2"
voyager = "1.0.0-rc03"
imageLoader = "1.6.0"

#Android Versions

#Desktop Versions
kamel = "0.4.0"

androidxCore = "1.7.0"
material = "1.6.0"
appCompat = "1.4.1"
constraintLayout = "2.1.4"
compose = "1.2.0-alpha08"
composeMaterial3 = "1.0.0-alpha13"
composeActivity = "1.4.0"
composeConstraintLayout = "1.0.0-rc01"
accompanist = "0.25.1"
navigation = "2.4.0-alpha02"
lifecycle = "2.3.1"
coil = "1.4.0"
palette = "1.0.0"
paging = "3.0.0"
coroutines = "1.5.2"
firebaseBOM = "30.3.1"
composeRatingBar = "1.1.1"
leakCanary = "2.9.1"
pagingCompose = "1.0.0-alpha14"
oneBoneToolbar = "2.3.4"

jUnit = "4.13.2"
truth = "1.1.3"
robolectric = "4.10.3"
jUnitKtx = "1.1.2"
espresso = "3.3.0"
test = "1.3.0"
kotlinTest = "1.1.51"
archTestCore = "2.1.0"
turbine = "0.12.3"
composeMultiplatform = "1.4.1"
kotlinxAtomicfu = "0.18.5"

[plugins]
ktLint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleVersionUpdates = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionUpdate" }
#kotlinX-testResources = { id = "com.goncalossilva.resources", version.ref = "kotlinxTestResources" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
nativeCocoapod = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle" }
android-application = { id = "com.android.application", version.ref = "gradle" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinX-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kmp-NativeCoroutines-plugin = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "kmpNativeCoroutines" }
sqlDelight-plugin = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

googleServices-plugin = { id = "com.google.gms.google-services", version.ref = "googleServices" }

firebase-crashlytics-plugin = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebase-appDistribution-plugin = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistribution" }
firebase-performance-plugin = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerformance" }

[libraries]
#Kotlin Multiplatform Lib Dependencies
kotlinX-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
kotlinX-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
sqlDelight = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDelight-coroutine = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelight-JVM = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kotlinX-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
multiplatformSettings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }
multiplatformSettings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatformSettings" }
kamel = { module = "com.alialbaali.kamel:kamel-image", version.ref = "kamel" }
voyager-core = { module = "cafe.adriel.voyager:voyager-core", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
imageLoader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoader" }
kotlinX-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomicfu" }

#Android Lib Dependencies
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
androidX-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
material = { module = "com.google.android.material:material", version.ref = "material" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemUIController = { module = "com.google.accompanist:accompanist-systemuicontroller", version = "0.17.0" }
accompanist-materialPlaceHolder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-pagerIndicator = { module = "com.google.accompanist:accompanist-pager-indicators", version = "0.22.0-rc" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
palette = { module = "androidx.palette:palette", version.ref = "palette" }
compose-ratingBar = { module = "com.github.a914-gowtham:compose-ratingbar", version.ref = "composeRatingBar" }
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
firebase-BOM = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBOM" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-performance = { module = "com.google.firebase:firebase-perf" }
oneBoneToolbar = { module = "me.onebone:toolbar-compose", version.ref = "oneBoneToolbar" }

#Tests Lib Dependencies
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
# kotlinX-testResources = { module = "com.goncalossilva:resources", version.ref = "kotlinxTestResources" }
kotlinX-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

jUnit = { module = "junit:junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }
googleTruth = { module = "com.google.truth:truth", version.ref = "truth" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
jUnitKtx = { module = "androidx.test.ext:junit-ktx", version.ref = "jUnitKtx" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
test-core = { module = "androidx.test:core-ktx", version.ref = "test" }
archTestCore = { module = "androidx.arch.core:core-testing", version.ref = "archTestCore" }
test-rules = { module = "androidx.test:rules", version.ref = "test" }
test-runner = { module = "androidx.test:runner", version.ref = "test" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }