name: Deploy Android Debug

on:
  push:
    branches:
      [firebase-intergration]
  workflow_dispatch:
    inputs:
      versionCode:
        description: 'Version Code (eg. 123)'
        required: true
      versionName:
        description: 'Version Name (eg 1.2.3)'
        required: true

env:
  VERSION_CODE: ${{ github.event.inputs.versionCode }}
  VERSION_NAME: ${{ github.event.inputs.versionName }}

jobs:

  build:
    name: ðŸ”¨ Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace


  deploy:
    name: ðŸš€ Deploy to Firebase App Distribution
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: production #testers
          file: appAndroid/build/outputs/apk/debug/appAndroid-debug.apk
